/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#define PORTA_BASE				0x00000000

#define	PORTA_DATAI_REG_ADDR		(PORTA_BASE+0x0)
#define	PORTA_DATAO_REG_ADDR		(PORTA_BASE+0x4)
#define	PORTA_DIR_REG_ADDR		(PORTA_BASE+0x8)
#define	PORTA_ICR_REG_ADDR		(PORTA_BASE+0xf00)
#define	PORTA_RIS_REG_ADDR		(PORTA_BASE+0xf04)
#define	PORTA_IM_REG_ADDR		(PORTA_BASE+0xf08)
#define	PORTA_MIS_REG_ADDR		(PORTA_BASE+0xf0c)

#define PORTA_DATAI_REG_DATAI		0
#define PORTA_DATAI_REG_DATAI_LEN	8
#define PORTA_DATAO_REG_DATAO		0
#define PORTA_DATAO_REG_DATAO_LEN	8
#define PORTA_DIR_REG_DIR		0
#define PORTA_DIR_REG_DIR_LEN	8
#define INT_PIN0_HI_FLAG	0x1
#define INT_PIN1_HI_FLAG	0x2
#define INT_PIN2_HI_FLAG	0x4
#define INT_PIN3_HI_FLAG	0x8
#define INT_PIN4_HI_FLAG	0x10
#define INT_PIN5_HI_FLAG	0x20
#define INT_PIN6_HI_FLAG	0x40
#define INT_PIN7_HI_FLAG	0x80
#define INT_PIN0_LO_FLAG	0x100
#define INT_PIN1_LO_FLAG	0x200
#define INT_PIN2_LO_FLAG	0x400
#define INT_PIN3_LO_FLAG	0x800
#define INT_PIN4_LO_FLAG	0x1000
#define INT_PIN5_LO_FLAG	0x2000
#define INT_PIN6_LO_FLAG	0x4000
#define INT_PIN7_LO_FLAG	0x8000
#define INT_PIN0_PE_FLAG	0x10000
#define INT_PIN1_PE_FLAG	0x20000
#define INT_PIN2_PE_FLAG	0x40000
#define INT_PIN3_PE_FLAG	0x80000
#define INT_PIN4_PE_FLAG	0x100000
#define INT_PIN5_PE_FLAG	0x200000
#define INT_PIN6_PE_FLAG	0x400000
#define INT_PIN7_PE_FLAG	0x800000
#define INT_PIN0_NE_FLAG	0x1000000
#define INT_PIN1_NE_FLAG	0x2000000
#define INT_PIN2_NE_FLAG	0x4000000
#define INT_PIN3_NE_FLAG	0x8000000
#define INT_PIN4_NE_FLAG	0x10000000
#define INT_PIN5_NE_FLAG	0x20000000
#define INT_PIN6_NE_FLAG	0x40000000
#define INT_PIN7_NE_FLAG	0x80000000

volatile unsigned int * porta_DATAO_REG	= (volatile unsigned int *) PORTA_DATAO_REG_ADDR;
volatile unsigned int * porta_DIR_REG	= (volatile unsigned int *) PORTA_DIR_REG_ADDR;
volatile unsigned int * porta_RIS_REG	= (volatile unsigned int *) PORTA_RIS_REG_ADDR;
volatile unsigned int * porta_ICR_REG	= (volatile unsigned int *) PORTA_ICR_REG_ADDR;
volatile unsigned int * porta_IM_REG	= (volatile unsigned int *) PORTA_IM_REG_ADDR;
