/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py on 2023-11-26

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/
#ifndef EF_GPIO_REGS_H
#define EF_GPIO_REGS_H


#ifndef IO_TYPES
#define IO_TYPES
#define   __R     volatile const unsigned int
#define   __W     volatile       unsigned int
#define   __RW    volatile       unsigned int
#endif

#define EF_GPIO_DATAI_REG_DATAI		0
#define EF_GPIO_DATAI_REG_DATAI_LEN	8
#define EF_GPIO_DATAO_REG_DATAO		0
#define EF_GPIO_DATAO_REG_DATAO_LEN	8
#define EF_GPIO_DIR_REG_DIR		0
#define EF_GPIO_DIR_REG_DIR_LEN	8
#define EF_GPIO_PIN0_HI_FLAG	0x1
#define EF_GPIO_PIN1_HI_FLAG	0x2
#define EF_GPIO_PIN2_HI_FLAG	0x4
#define EF_GPIO_PIN3_HI_FLAG	0x8
#define EF_GPIO_PIN4_HI_FLAG	0x10
#define EF_GPIO_PIN5_HI_FLAG	0x20
#define EF_GPIO_PIN6_HI_FLAG	0x40
#define EF_GPIO_PIN7_HI_FLAG	0x80
#define EF_GPIO_PIN0_LO_FLAG	0x100
#define EF_GPIO_PIN1_LO_FLAG	0x200
#define EF_GPIO_PIN2_LO_FLAG	0x400
#define EF_GPIO_PIN3_LO_FLAG	0x800
#define EF_GPIO_PIN4_LO_FLAG	0x1000
#define EF_GPIO_PIN5_LO_FLAG	0x2000
#define EF_GPIO_PIN6_LO_FLAG	0x4000
#define EF_GPIO_PIN7_LO_FLAG	0x8000
#define EF_GPIO_PIN0_PE_FLAG	0x10000
#define EF_GPIO_PIN1_PE_FLAG	0x20000
#define EF_GPIO_PIN2_PE_FLAG	0x40000
#define EF_GPIO_PIN3_PE_FLAG	0x80000
#define EF_GPIO_PIN4_PE_FLAG	0x100000
#define EF_GPIO_PIN5_PE_FLAG	0x200000
#define EF_GPIO_PIN6_PE_FLAG	0x400000
#define EF_GPIO_PIN7_PE_FLAG	0x800000
#define EF_GPIO_PIN0_NE_FLAG	0x1000000
#define EF_GPIO_PIN1_NE_FLAG	0x2000000
#define EF_GPIO_PIN2_NE_FLAG	0x4000000
#define EF_GPIO_PIN3_NE_FLAG	0x8000000
#define EF_GPIO_PIN4_NE_FLAG	0x10000000
#define EF_GPIO_PIN5_NE_FLAG	0x20000000
#define EF_GPIO_PIN6_NE_FLAG	0x40000000
#define EF_GPIO_PIN7_NE_FLAG	0x80000000

typedef struct _EF_GPIO_TYPE_ {
	__R 	datai;
	__RW	datao;
	__RW	dir;
	__R 	reserved[957];
	__W 	icr;
	__R 	ris;
	__RW	im;
	__R 	mis;
} EF_GPIO_TYPE;

#endif