SIM-RTL:
	iverilog EF_GPIO8_apb_tb.v ../../hdl/rtl/EF_GPIO8.v ../../hdl/rtl/bus_wrappers/EF_GPIO8_apb.v 
	./a.out

SIM-GL:
	iverilog EF_GPIO8_apb_tb.v ../../hdl/gl/sky130/EF_GPIO8_apb.gl.v ../../util/tech/sky130/sky130_hd.v
	./a.out
