name: Run UVM all tests

on:
  push: # This now triggers on pushes to any branch
  pull_request: # This now triggers on pull requests to any branch

jobs:
  Run-IP-Tests:
    uses: efabless/EF_UVM/.github/workflows/run_IP.yaml@support-ip-ci
    with:
      url: "n/a"
      test-names: "gpio8_all_out_test gpio8_all_in_test"
      name: EF_GPIO
      buses: APB
      is-ip: true
