name: Run UVM all tests

on:
  push: # This now triggers on pushes to any branch
  pull_request: # This now triggers on pull requests to any branch

jobs:
  Test:
    runs-on: ubuntu-latest
    outputs:
      IPs: ${{ steps.set-IPs-matrix.outputs.IPs }}
    steps:
      - name: Fetch Supported Buses
        id: fetch_buses
        uses: efabless/EF_UVM/.github/actions/get-bus@support-ip-ci
      - name: Check Output
        runs: echo ${{ steps.fetch_buses.outputs.buses }}
  #  Run-IP-Tests:
  #    uses: efabless/EF_UVM/.github/workflows/run_IP.yaml@support-ip-ci
  #    with:
  #      url: "n/a"
  #      test-names: "gpio8_all_out_test gpio8_all_in_test"
  #      name: EF_GPIO
  #      buses: APB
  #      is-ip: true
